# 本地服务访问
server:
  # 服务端口
  port: 8080
  # 服务IP
  address: 0.0.0.0

spring:
  application:
    # 应用服务名
    name: web
#  profiles:
#    active: db
  # redis连接配置
  redis:
    host: 192.168.88.100
    port: 6379
    database: 0

# 配置日志
logging:
#  level:
#    com.netflix: info
#    org.springframework.boot: info
#    # log 级别
#    org.springframework.cloud.gateway: debug
  config: classpath:log4j2.xml

# 是否启用springboot的debug调试模式，会打印详细日志信息
debug: true
